In [2]:
import pandas as pd

In [2]:
elec_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/4H_elec_segment_0.csv'
gas_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/6H_gas_segment_0.csv'
water_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/8H_water_segment_0.csv'
weather_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/4H_weather_segment_0.csv'

Electricity

In [8]:
clusters = [17, 1, 17, 17, 17, 17, 14, 14, 22, 22, 17, 1, 14, 36, 14, 14, 1, 17, 22, 14, 1, 36, 22, 14, 17, 17, 26, 17, 14, 17, 14, 14, 14, 14, 14, 14, 36, 22, 17, 17, 14, 14, 22, 22, 1, 14, 17, 14, 14, 1, 22, 36, 22, 1, 22, 14, 22, 14, 22, 14, 22]

In [9]:
data = pd.read_csv(elec_path)
data.head()

,Unnamed: 0,E0,E1,E2,E3,E4,E5,cluster
0,2012-04-02,0.599153,0.318122,0.223861,0.266793,0.156104,0.136609,39
1,2012-04-03,0.308922,0.282783,0.152234,0.208017,0.206046,0.396612,1
2,2012-04-04,0.474883,0.325496,0.265041,0.304249,0.131790,0.144787,39
3,2012-04-05,0.447941,0.402234,0.231746,0.345575,0.172167,0.141647,39
4,2012-04-06,0.147926,0.527672,0.259930,0.296510,0.072284,0.119305,39

In [6]:
data['cluster'] = clusters

In [7]:
data.to_csv(elec_path, index=False)

Gas

In [83]:
clusters = [12, 4, 42, 12, 4, 42, 42, 42, 4, 12, 12, 12, 12, 13, 42, 4, 4, 42, 42, 4, 4, 42, 12, 12, 42, 42, 42, 4, 42, 12, 35, 35, 35, 35, 35, 35, 13, 42, 12, 12, 42, 42, 42, 42, 12, 12, 4, 4, 42, 12, 4, 4, 4, 4, 4, 13, 12, 42, 42, 42, 4]

In [84]:
data = pd.read_csv(gas_path)
data.head()

   Unnamed: 0        G0        G1        G2        G3  cluster
0  2012-04-02  0.403226  0.000000  0.107527  0.037634       15
1  2012-04-03  0.333333  0.016129  0.032258  0.102151       15
2  2012-04-04  0.306452  0.075269  0.048387  0.064516       15
3  2012-04-05  0.387097  0.000000  0.048387  0.059140       15
4  2012-04-06  0.344086  0.000000  0.059140  0.123656       15

In [85]:
data['cluster'] = clusters

In [86]:
data.head()

   Unnamed: 0        G0        G1        G2        G3  cluster
0  2012-04-02  0.403226  0.000000  0.107527  0.037634       12
1  2012-04-03  0.333333  0.016129  0.032258  0.102151        4
2  2012-04-04  0.306452  0.075269  0.048387  0.064516       42
3  2012-04-05  0.387097  0.000000  0.048387  0.059140       12
4  2012-04-06  0.344086  0.000000  0.059140  0.123656        4

In [87]:
data.to_csv(gas_path, index=False)

Water

In [88]:
clusters = [26, 41, 26, 26, 41, 41, 41, 41, 26, 10, 10, 41, 10, 13, 41, 41, 26, 10, 41, 26, 13, 26, 10, 10, 41, 41, 26, 10, 41, 10, 33, 33, 33, 33, 33, 33, 13, 41, 10, 10, 26, 41, 41, 10, 26, 10, 26, 26, 26, 26, 26, 26, 26, 26, 26, 13, 10, 41, 41, 41, 26]

In [89]:
data = pd.read_csv(water_path)
data.head()

   Unnamed: 0       Wa0       Wa1       Wa2  cluster
0  2012-04-02  0.161316  0.023723  0.087775        3
1  2012-04-03  0.149455  0.016606  0.049818        3
2  2012-04-04  0.170805  0.014234  0.080658        3
3  2012-04-05  0.161316  0.014234  0.066424        3
4  2012-04-06  0.149455  0.018978  0.064052        3

In [90]:
data['cluster'] = clusters

In [91]:
data.head()

   Unnamed: 0       Wa0       Wa1       Wa2  cluster
0  2012-04-02  0.161316  0.023723  0.087775       26
1  2012-04-03  0.149455  0.016606  0.049818       41
2  2012-04-04  0.170805  0.014234  0.080658       26
3  2012-04-05  0.161316  0.014234  0.066424       26
4  2012-04-06  0.149455  0.018978  0.064052       41

In [92]:
data.to_csv(water_path, index=False)

Weather

In [103]:
clusters = [12, 1, 4, 4, 4, 4, 12, 52, 52, 27, 12, 12, 12, 12, 12, 4, 12, 12, 12, 12, 52, 27, 27, 27, 27, 12, 27, 27, 12, 12, 12, 12, 12, 12, 52, 52, 55, 12, 12, 12, 52, 55, 55, 55, 52, 52, 52, 52, 27, 55, 27, 52, 52, 55, 55, 55, 55, 52, 27, 55, 55]

In [104]:
data = pd.read_csv(weather_path)
data.head()

,Unnamed: 0,We0,We1,We2,We3,We4,We5,cluster
0,2012-04-02,0.446868,0.453202,0.498944,0.593948,0.572132,0.531316,12
1,2012-04-03,0.508093,0.502463,0.409571,0.444053,0.441239,0.363125,1
2,2012-04-04,0.323716,0.325827,0.431386,0.467277,0.448276,0.396904,4
3,2012-04-05,0.340605,0.374384,0.434905,0.490500,0.475018,0.405348,4
4,2012-04-06,0.332864,0.365236,0.441239,0.503871,0.500352,0.403941,4

In [105]:
data['cluster'] = clusters

In [106]:
data.head()

,Unnamed: 0,We0,We1,We2,We3,We4,We5,cluster
0,2012-04-02,0.446868,0.453202,0.498944,0.593948,0.572132,0.531316,12
1,2012-04-03,0.508093,0.502463,0.409571,0.444053,0.441239,0.363125,1
2,2012-04-04,0.323716,0.325827,0.431386,0.467277,0.448276,0.396904,4
3,2012-04-05,0.340605,0.374384,0.434905,0.490500,0.475018,0.405348,4
4,2012-04-06,0.332864,0.365236,0.441239,0.503871,0.500352,0.403941,4

In [107]:
data.to_csv(weather_path, index=False)

In [16]:
path = 'C:\\git-repo\\EdgeCluster\\results\\ampds\\elec\\3\\tabular\\final_clustering.csv'

In [17]:
df = pd.read_csv(path)

In [18]:
df.head()

,E0,E1,E2,E3,E4,E5,cluster,is_included,target,segment,stream
0,0.599153,0.318122,0.223861,0.266793,0.156104,0.136609,7,True,NaN,0,-1
1,0.308922,0.282783,0.152234,0.208017,0.206046,0.396612,7,True,NaN,0,-1
2,0.474883,0.325496,0.265041,0.304249,0.131790,0.144787,7,True,NaN,0,-1
3,0.447941,0.402234,0.231746,0.345575,0.172167,0.141647,7,True,NaN,0,-1
4,0.147926,0.527672,0.259930,0.296510,0.072284,0.119305,7,True,NaN,0,-1

In [24]:
from sklearn.metrics import pairwise_distances, silhouette_score

data = df[df["segment"]==11]
clusters = data['cluster']
data = data[data.columns[:-5]]
print(data.head())
distances = pairwise_distances(data,data, 'euclidean')

silhouette_score(distances, clusters, metric='precomputed')

           E0        E1        E2        E3        E4        E5
681  0.325935  0.185018  0.028183  0.030155  0.150628  0.355286
682  0.572211  0.237223  0.039428  0.035412  0.151358  0.284317
683  0.288697  0.189544  0.026577  0.281031  0.113391  0.043589
684  0.384784  0.198306  0.029863  0.131571  0.107842  0.114559
685  0.644933  0.186916  0.035704  0.092436  0.043589  0.060529

0.12371696386531544