In [1]:
import pandas as pd

/tmp/ipykernel_85094/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
elec_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/4H_elec_segment_0.csv'
gas_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/6H_gas_segment_0.csv'
water_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/8H_water_segment_0.csv'
weather_path = '/Users/milenaangelova/git-repo/EdgeCluster/data/ampds/initial_clusterings/4H_weather_segment_0.csv'

Electricity

In [8]:
clusters = [17, 1, 17, 17, 17, 17, 14, 14, 22, 22, 17, 1, 14, 36, 14, 14, 1, 17, 22, 14, 1, 36, 22, 14, 17, 17, 26, 17, 14, 17, 14, 14, 14, 14, 14, 14, 36, 22, 17, 17, 14, 14, 22, 22, 1, 14, 17, 14, 14, 1, 22, 36, 22, 1, 22, 14, 22, 14, 22, 14, 22]

In [9]:
data = pd.read_csv(elec_path)
data.head()

,Unnamed: 0,E0,E1,E2,E3,E4,E5,cluster
0,2012-04-02,0.599153,0.318122,0.223861,0.266793,0.156104,0.136609,39
1,2012-04-03,0.308922,0.282783,0.152234,0.208017,0.206046,0.396612,1
2,2012-04-04,0.474883,0.325496,0.265041,0.304249,0.131790,0.144787,39
3,2012-04-05,0.447941,0.402234,0.231746,0.345575,0.172167,0.141647,39
4,2012-04-06,0.147926,0.527672,0.259930,0.296510,0.072284,0.119305,39

In [6]:
data['cluster'] = clusters

In [7]:
data.to_csv(elec_path, index=False)

Gas

In [83]:
clusters = [12, 4, 42, 12, 4, 42, 42, 42, 4, 12, 12, 12, 12, 13, 42, 4, 4, 42, 42, 4, 4, 42, 12, 12, 42, 42, 42, 4, 42, 12, 35, 35, 35, 35, 35, 35, 13, 42, 12, 12, 42, 42, 42, 42, 12, 12, 4, 4, 42, 12, 4, 4, 4, 4, 4, 13, 12, 42, 42, 42, 4]

In [84]:
data = pd.read_csv(gas_path)
data.head()

   Unnamed: 0        G0        G1        G2        G3  cluster
0  2012-04-02  0.403226  0.000000  0.107527  0.037634       15
1  2012-04-03  0.333333  0.016129  0.032258  0.102151       15
2  2012-04-04  0.306452  0.075269  0.048387  0.064516       15
3  2012-04-05  0.387097  0.000000  0.048387  0.059140       15
4  2012-04-06  0.344086  0.000000  0.059140  0.123656       15

In [85]:
data['cluster'] = clusters

In [86]:
data.head()

   Unnamed: 0        G0        G1        G2        G3  cluster
0  2012-04-02  0.403226  0.000000  0.107527  0.037634       12
1  2012-04-03  0.333333  0.016129  0.032258  0.102151        4
2  2012-04-04  0.306452  0.075269  0.048387  0.064516       42
3  2012-04-05  0.387097  0.000000  0.048387  0.059140       12
4  2012-04-06  0.344086  0.000000  0.059140  0.123656        4

In [87]:
data.to_csv(gas_path, index=False)

Water

In [88]:
clusters = [26, 41, 26, 26, 41, 41, 41, 41, 26, 10, 10, 41, 10, 13, 41, 41, 26, 10, 41, 26, 13, 26, 10, 10, 41, 41, 26, 10, 41, 10, 33, 33, 33, 33, 33, 33, 13, 41, 10, 10, 26, 41, 41, 10, 26, 10, 26, 26, 26, 26, 26, 26, 26, 26, 26, 13, 10, 41, 41, 41, 26]

In [89]:
data = pd.read_csv(water_path)
data.head()

   Unnamed: 0       Wa0       Wa1       Wa2  cluster
0  2012-04-02  0.161316  0.023723  0.087775        3
1  2012-04-03  0.149455  0.016606  0.049818        3
2  2012-04-04  0.170805  0.014234  0.080658        3
3  2012-04-05  0.161316  0.014234  0.066424        3
4  2012-04-06  0.149455  0.018978  0.064052        3

In [90]:
data['cluster'] = clusters

In [91]:
data.head()

   Unnamed: 0       Wa0       Wa1       Wa2  cluster
0  2012-04-02  0.161316  0.023723  0.087775       26
1  2012-04-03  0.149455  0.016606  0.049818       41
2  2012-04-04  0.170805  0.014234  0.080658       26
3  2012-04-05  0.161316  0.014234  0.066424       26
4  2012-04-06  0.149455  0.018978  0.064052       41

In [92]:
data.to_csv(water_path, index=False)

Weather

In [103]:
clusters = [12, 1, 4, 4, 4, 4, 12, 52, 52, 27, 12, 12, 12, 12, 12, 4, 12, 12, 12, 12, 52, 27, 27, 27, 27, 12, 27, 27, 12, 12, 12, 12, 12, 12, 52, 52, 55, 12, 12, 12, 52, 55, 55, 55, 52, 52, 52, 52, 27, 55, 27, 52, 52, 55, 55, 55, 55, 52, 27, 55, 55]

In [104]:
data = pd.read_csv(weather_path)
data.head()

,Unnamed: 0,We0,We1,We2,We3,We4,We5,cluster
0,2012-04-02,0.446868,0.453202,0.498944,0.593948,0.572132,0.531316,12
1,2012-04-03,0.508093,0.502463,0.409571,0.444053,0.441239,0.363125,1
2,2012-04-04,0.323716,0.325827,0.431386,0.467277,0.448276,0.396904,4
3,2012-04-05,0.340605,0.374384,0.434905,0.490500,0.475018,0.405348,4
4,2012-04-06,0.332864,0.365236,0.441239,0.503871,0.500352,0.403941,4

In [105]:
data['cluster'] = clusters

In [106]:
data.head()

,Unnamed: 0,We0,We1,We2,We3,We4,We5,cluster
0,2012-04-02,0.446868,0.453202,0.498944,0.593948,0.572132,0.531316,12
1,2012-04-03,0.508093,0.502463,0.409571,0.444053,0.441239,0.363125,1
2,2012-04-04,0.323716,0.325827,0.431386,0.467277,0.448276,0.396904,4
3,2012-04-05,0.340605,0.374384,0.434905,0.490500,0.475018,0.405348,4
4,2012-04-06,0.332864,0.365236,0.441239,0.503871,0.500352,0.403941,4

In [107]:
data.to_csv(weather_path, index=False)

In [1]:
from scipy.sparse.csgraph import minimum_spanning_tree
import numpy as np
import copy

In [2]:
def IC_av(distance_matrix = None, labels = None):
    """Calculates Intra Cluster distance average of a clustering solution.

    Args:
        distance_matrix: 2-dimensional (n * n) matrix of Pandas Dataframe type containing distances between all nodes.
        labels: Clustering labels to assign each node.
    Returns:
        List containing total IC_av distance and each individual IC_av distance for each cluster.
    Raises:
        TypeError: if distance_matrix is not a Pandas.Dataframe.
        ValueError: if distance_matrix or labels is of None value.
    """
    # if distance_matrix is None:
    #     raise ValueError("distance_matrix cannot be None value")
    # if not isinstance(distance_matrix, pd.DataFrame):
    #     raise TypeError("distance_matrix must be DataFrame")
    # if labels is None:
    #     raise ValueError("labels cannot be None value")


    # MST of the distance matrix
    mst = minimum_spanning_tree(distance_matrix)

    MED_matrix = pd.DataFrame(fast_IC_av(mst))
    
    IC_score = 0
    IC_scores = [0]
    clusters = list(sorted(set(labels))) # Get clusterlabels from labels

    MED_matrix.reset_index
    MED_matrix['clusters'] = labels


    # Traverse the mst for the largest edge and calculate the IC_av score
    for cluster in clusters:
        nodes = MED_matrix.loc[MED_matrix['clusters'] == cluster].index.tolist()
        total = 0
        for i in range(len(nodes)):
            for j in range(i+1, len(nodes)):
                total += MED_matrix[i][j]
                #total += MED_matrix[i][j]**2

        total /= len(nodes)
        IC_score += total
        IC_scores.append(total)

    # Returns total IC_av score and individual IC_av scores for each cluster
    IC_scores[0] = IC_score
    return IC_scores

def d_med(tree, i, j):
    # traverse from i to j and return the max edge value
    return traverse(tree, i, i, j)

def traverse(tree, current, parent, target):
    if current == target:   # base case
        return tree[current][parent]

    # Get indexes that connect this node to the others except the parent
    children = [x for x in range(len(tree[current])) if tree[current][x] != 0 and x != parent]

    for child in children:
        dist = traverse(tree, child, current, target)
        if dist > 0:
            if dist > tree[current][parent]:
                return dist
            return tree[current][parent]

    return -1

def fast_IC_av(mst):
    """Returns the MED distance matrix for all nodes in the graph"""

    N = mst.shape[0]

    global graph
    graph = mst.toarray()
    
    # Preparation
    # for a non-directed graph, we need to symmetrize the distances
    # this is necessary since the minimum spanning tree only delivers edges in one direction
    for i in range(N):
        for j in range(i + 1, N):
            if graph[j, i] >= graph[i, j]:
                graph[i, j] = graph[j, i]
            else:
                graph[j, i] = graph[i, j]


    # 1) find all leaf nodes
    global leaf_list
    leaf_list = find_leaves(graph)
    # print("Leaves", leaf_list)

    # Set all distances with no direct connection to infinity
    graph[np.where(graph == 0)] = np.nan

    # Graph[i,i] should be zero
    graph.flat[::N + 1] = 0
    
    # 2) Store the results
    # MED_matrix saves the MED from node a to b 
    # MED is positive and symmetrical
    # Add takes the initial distances from graph
    global MED_matrix
    MED_matrix = copy.deepcopy(graph)
    

    # 3) Create a path dictionary to store started paths
    global path_list
    path_list = {}
    
    # Follow the paths while there are still leaf nodes
    while(leaf_list):
        first_node = leaf_list.pop()
        current_path = [first_node]

        neighbor_list = find_neighbors(graph, first_node, current_path)

        # since that is a leaf there should be only one neighbor
        assert len(neighbor_list) == 1

        # Calculate the distance to the next node
        dist = graph[first_node, neighbor_list[0]]

        follow_path(next_node=neighbor_list[0], current_path=current_path, dist=dist)

    return MED_matrix


def follow_path(next_node, current_path, dist):

    # Update the current path with the distance to the next node
    update_distances_node_centered(dist=dist, visited_list=current_path, shape=graph.shape[0], next_node=next_node)

    # Add the next element to the current path
    current_path.append(next_node)

    # Find path to the next elements
    neighbor_list = find_neighbors(graph, next_node, current_path)

    # Check whether an intersection or a leaf
    if not neighbor_list:
        # Remove the leaf from the leaf-list
        # Since it doesn't have to be a leaf it could be also stuck somewhere between known parts
        if next_node in leaf_list:
            leaf_list.remove(next_node)
        return

    elif len(neighbor_list) == 1:
        dist = graph[next_node, neighbor_list[0]]
        follow_path(next_node=neighbor_list[0], current_path=current_path, dist=dist)
    else:
        # Intersection case
        # Check if the current node is already in the dictionary
        if path_list.get(next_node):
            # Print already stored
            # Join lists and follow the path
            current_path = current_path + path_list.get(next_node)

            # Find the next way which is not in the joined list
            dest_node = [x for x in neighbor_list if x not in current_path]

            if not dest_node:
                # No more paths so the algorithm is finished
                print("No way to go. Empty join result")
                return
            elif len(dest_node) > 1:
                # Store the current path in the dictionary
                path_list.update({next_node:current_path})
                # Start again at the next leaf
                return

            else:
                # Follow the path with the now extended list
                # With the only left node to go
                dist = graph[next_node, dest_node[0]]
                follow_path(next_node=dest_node[0], current_path=current_path, dist=dist)

        else:
            # Store the current path in the dictionary
            path_list.update({next_node:current_path})
            # Start again at the next leaf
            return


def update_distances(dist, visited_list, shape):
    for node in range(shape):
        # Do not update distances in the already visited paths
        if node in visited_list:
            continue

        # Go through all the visited nodes and compare the distances, 
        # in case it is bigger perform an update
        for vis_node in visited_list:
            MED_matrix[vis_node, node] = np.nanmax([MED_matrix[vis_node, node], dist])
            MED_matrix[node, vis_node] = MED_matrix[vis_node, node]

def update_distances_node_centered(dist, visited_list, shape, next_node):
    # Going through the already visited nodes
    for vis_node in visited_list:
        # In case we already have a bigger distance to the new added node
        # we can skip this node since nothing will change
        # print(MED_matrix[vis_node, next_node], dist)
        if MED_matrix[vis_node, next_node] <= dist or np.isnan(MED_matrix[vis_node, next_node]):
            # Go through all nodes and update the distance
            for node in range(shape):
                # Do not update distances in the already visited paths
                if node in visited_list:
                    continue
                MED_matrix[vis_node, node] = np.nanmax([MED_matrix[vis_node, node], dist])
                MED_matrix[node, vis_node] = MED_matrix[vis_node, node]
        #else:
        #    print(next_node, visited_list, dist, vis_node)
        #    print(MED_matrix)

        # Go through all the visited nodes and compare the distances, 
        # in case it is bigger perform an update


def find_neighbors(graph, node, current_path):
    neighbor_list = []
    for ii in range(graph.shape[0]):
        if not np.isnan(graph[node, ii]) and ii not in current_path:
            neighbor_list.append(ii)

    return neighbor_list
    

def find_leaves(graph):
    """Returns a list of all leaves"""
    
    leaf_list = []

    for row in range(graph.shape[0]):
        # print(np.count_nonzero(graph[row]))
        # one non-zero element means that there is only one connection to another node
        # making it to a leaf
        if np.count_nonzero(graph[row]) == 1:
            leaf_list.append(row)

        # Iris data set 54 leaves, so more than one third
    return leaf_list

In [8]:

import pandas as pd
import os 
from sklearn.metrics import pairwise_distances,silhouette_score

result_metrics = {}

def calculate_distances(data):
    return pairwise_distances(data,data)

def eda_clustering(window=30, data_type='elec', is_included=False):
    base_dir = f'../results/ampds/{data_type}/{window}/tabular/'
    df = pd.read_csv(os.path.join(base_dir, 'final_clustering.csv'), encoding='utf-8')
    # df = df[df['segment']<=num_segments]

    if is_included:
        df = df[df['is_included']==True]

    distances = calculate_distances(df[df.columns[:-6]].to_numpy(copy=True))
    if len(df['cluster'].unique()) > 1:
        SI = silhouette_score(distances, df['cluster'])
    else:
        SI = None
    # IC = IC_av(distances, df['cluster'])
 
    result_metrics[window] = [SI, int(len(df['cluster'].unique()))]

In [9]:
for window in [3, 5, 7]:
    # eda_clustering(window=window, data_type='gas', is_included=False)
    eda_clustering(window=window, data_type='gas', is_included=True)

results_df = pd.DataFrame(result_metrics).T
results_df.columns = ['SI', 'cluster_count']
results_df

         SI  cluster_count
3 -0.096896           12.0
5 -0.157494            7.0
7 -0.162175            6.0

In [6]:
for window in [3, 5, 7]:
    # eda_clustering(window=window, data_type='elec', is_included=False)
    eda_clustering(window=window, data_type='gas', is_included=True)

results_df = pd.DataFrame(result_metrics).T
results_df.columns = ['SI','IC', 'cluster_count']
results_df

ZeroDivisionError: division by zero

In [7]:
for window in [3, 5, 7]:
    eda_clustering(window=window, data_type='water', is_included=False)
    # eda_clustering(window=window, data_type='gas', is_included=True)

results_df = pd.DataFrame(result_metrics).T
results_df.columns = ['SI','IC', 'cluster_count']
results_df

In [ ]:
for window in [3, 5, 7]:
    eda_clustering(window=window, data_type='weather', is_included=False)
    # eda_clustering(window=window, data_type='gas', is_included=True)

results_df = pd.DataFrame(result_metrics).T
results_df.columns = ['SI','IC', 'cluster_count']
results_df

         SI                                                 IC cluster_count
3  0.033727  [16.160110081959477, 10.17636449892202, 5.7829...             3
5 -0.528572  [16.37091752368633, 15.415555887776192, 0.1816...             5
7 -0.231152  [16.410020934106264, 15.502832784351995, 0.587...             3